// ─────────────────────────────────────────────
//  ROLES & PERMISSIONS
// ─────────────────────────────────────────────

const ROLES = {
  HQ_ADMIN:       'hq_admin',
  BRANCH_MANAGER: 'branch_manager',
  STAFF:          'staff',
};

// Which roles are allowed to perform which actions.
// Used by roleMiddleware to enforce access control.
const PERMISSIONS = {

  // ── USER MANAGEMENT ──────────────────────
  CREATE_USER:        [ROLES.HQ_ADMIN],
  VIEW_ALL_USERS:     [ROLES.HQ_ADMIN],
  DEACTIVATE_USER:    [ROLES.HQ_ADMIN],
  UPDATE_USER:        [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER],

  // ── BRANCH MANAGEMENT ────────────────────
  CREATE_BRANCH:      [ROLES.HQ_ADMIN],
  UPDATE_BRANCH:      [ROLES.HQ_ADMIN],
  VIEW_ALL_BRANCHES:  [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER],
  DEACTIVATE_BRANCH:  [ROLES.HQ_ADMIN],

  // ── ORDERS ───────────────────────────────
  CREATE_ORDER:       [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER, ROLES.STAFF],
  VIEW_ALL_ORDERS:    [ROLES.HQ_ADMIN],
  VIEW_BRANCH_ORDERS: [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER, ROLES.STAFF],
  UPDATE_ORDER_STATUS:[ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER, ROLES.STAFF],
  DELETE_ORDER:       [ROLES.HQ_ADMIN],

  // ── PAYMENTS ─────────────────────────────
  RECORD_PAYMENT:     [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER, ROLES.STAFF],
  VIEW_ALL_PAYMENTS:  [ROLES.HQ_ADMIN],
  VIEW_BRANCH_PAYMENTS:[ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER],
  FLAG_PAYMENT:       [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER],

  // ── INVENTORY ────────────────────────────
  ADD_INVENTORY:      [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER],
  VIEW_INVENTORY:     [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER, ROLES.STAFF],
  UPDATE_STOCK:       [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER],
  LOG_STOCK_USAGE:    [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER, ROLES.STAFF],
  RESTOCK_ITEM:       [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER],

  // ── MACHINES ─────────────────────────────
  ADD_MACHINE:        [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER],
  UPDATE_MACHINE:     [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER],
  LOG_MACHINE_USAGE:  [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER, ROLES.STAFF],

  // ── EXPENSES ─────────────────────────────
  RECORD_EXPENSE:     [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER],
  VIEW_EXPENSES:      [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER],
  DELETE_EXPENSE:     [ROLES.HQ_ADMIN],

  // ── REPORTS & DASHBOARD ──────────────────
  VIEW_HQ_DASHBOARD:  [ROLES.HQ_ADMIN],
  VIEW_BRANCH_DASHBOARD:[ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER],
  VIEW_REPORTS:       [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER],
  VIEW_FRAUD_REPORT:  [ROLES.HQ_ADMIN],
  VIEW_AUDIT_LOGS:    [ROLES.HQ_ADMIN],

  // ── CUSTOMERS ────────────────────────────
  CREATE_CUSTOMER:    [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER, ROLES.STAFF],
  VIEW_CUSTOMERS:     [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER, ROLES.STAFF],
  UPDATE_CUSTOMER:    [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER],

  // ── FEEDBACK ─────────────────────────────
  SUBMIT_FEEDBACK:    [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER, ROLES.STAFF],
  VIEW_FEEDBACK:      [ROLES.HQ_ADMIN, ROLES.BRANCH_MANAGER],
};

module.exports = { ROLES, PERMISSIONS };